services:
  frontend:
    build:
      context: ./frontend

    ports:
      - "5173:5173"

    environment:
      - VITE_API_URL=http://localhost:8000/api/v1

    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./backend

    ports:
      - "8000:8000"

    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/equiaudit
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/metrics')"]
      interval: 10s
      timeout: 5s
      retries: 10

  celery-worker:
    build:
      context: ./backend

    command: celery -A app.workers.celery_app.celery worker --loglevel=INFO

    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/equiaudit
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started

  celery-beat:
    build:
      context: ./backend

    command: celery -A app.workers.celery_app.celery beat --loglevel=INFO

    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/equiaudit
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started

  postgres:
    image: postgres:15

    restart: always

    environment:
      POSTGRES_DB: equiaudit

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  redis:
    image: redis:7

    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/equiaudit-dashboard.json
    depends_on:
      - prometheus

  nginx:
    build:
      context: ./infrastructure/nginx

    ports:
      - "80:80"

    depends_on:
      - frontend
      - backend
